//Autogenerated triple quantized liym file with draw function
int lilytricount = 2;
f32 lilyvertpos[] ATTRIBUTE_ALIGN(32) = {0.172300, 0.250357, -0.013525, -0.153122, -0.238010, 0.574337, -0.050151, -0.293111, -0.001295, 0.069329, 0.305458, 0.562107};
uint16_t lilyvertposidx[] = {0, 1, 2, 0, 3, 1};
f32 lilyvertnor[] ATTRIBUTE_ALIGN(32) = {0.908752, -0.367518, 0.197740};
uint16_t lilyvertnoridx[] = {0, 0, 0, 0, 0, 0};
f32 lilytexcord[] ATTRIBUTE_ALIGN(32) = {1.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 1.000000, 1.000000};
uint16_t lilytexcordidx[] = {0, 1, 2, 0, 3, 1};

void ag_draw_lily(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &lilyvertpos[0], 12);
	GX_SetArray(GX_VA_NRM, &lilyvertnor[0], 12);
	GX_SetArray(GX_VA_TEX0, &lilytexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_VNIDX16 | LV_TCIDX16, lilytricount, vtxfmt,
		NULL, NULL, lilyvertposidx,
		NULL, NULL, lilyvertnoridx,
		NULL, NULL, lilytexcordidx,
		NULL,
		NULL);
}

void ag_config_lily(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_VNIDX16 | LV_TCIDX16, vtxfmt);
}