//Autogenerated triple quantized liym file with draw function
int skateboartricount = 12;
f32 skateboarvertpos[] ATTRIBUTE_ALIGN(32) = {-0.127834, -0.317044, 0.021773, -0.127834, 0.317044, -0.021773, -0.127834, -0.317044, -0.021773, -0.127834, 0.317044, 0.021773, 0.127834, 0.317044, -0.021773, 0.127834, 0.317044, 0.021773, 0.127834, -0.317044, -0.021773, 0.127834, -0.317044, 0.021773};
uint16_t skateboarvertposidx[] = {0, 1, 2, 3, 4, 1, 5, 6, 4, 7, 2, 6, 4, 2, 1, 3, 7, 5, 0, 3, 1, 3, 5, 4, 5, 7, 6, 7, 0, 2, 4, 6, 2, 3, 0, 7};
f32 skateboarvertnor[] ATTRIBUTE_ALIGN(32) = {-0.577350, -0.577350, 0.577350, -0.577350, 0.577350, -0.577350, -0.577350, -0.577350, -0.577350, -0.577350, 0.577350, 0.577350, 0.577350, 0.577350, -0.577350, 0.577350, 0.577350, 0.577350, 0.577350, -0.577350, -0.577350, 0.577350, -0.577350, 0.577350};
uint16_t skateboarvertnoridx[] = {0, 1, 2, 3, 4, 1, 5, 6, 4, 7, 2, 6, 4, 2, 1, 3, 7, 5, 0, 3, 1, 3, 5, 4, 5, 7, 6, 7, 0, 2, 4, 6, 2, 3, 0, 7};

void ag_draw_skateboar(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &skateboarvertpos[0], 12);
	GX_SetArray(GX_VA_NRM, &skateboarvertnor[0], 12);
	drawArrConfig(LV_VPIDX16 | LV_VNIDX16, skateboartricount, vtxfmt,
		NULL, NULL, skateboarvertposidx,
		NULL, NULL, skateboarvertnoridx,
		NULL, NULL, NULL,
		NULL,
		NULL);
}

void ag_config_skateboar(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_VNIDX16, vtxfmt);
}